
# Run docker-compose -f docker-compose.prod.yml build
# Run docker-compose -f docker-compose.prod.yml up
# Live long and prosper

version: '3.7'

services:

  nginx:
    container_name: nginx-angular
    image: nginx-angular
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - "80:80"
      - "443:443"
    
    networks:
      - app-network
 
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge